# Generated by Django 4.0.4 on 2022-07-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icms_minas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icms_fora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icms_importado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_pro_ref', models.JSONField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('data_previsao', models.DateField()),
                ('prazo', models.CharField(max_length=30)),
                ('prazo_medio', models.IntegerField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loja', models.CharField(max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(max_length=2)),
                ('bonificacao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacao', models.TextField(blank=True, default=None, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='DadosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=20)),
                ('tamanho', models.CharField(max_length=20)),
                ('quant', models.IntegerField()),
                ('quant_baixa', models.IntegerField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('icms', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.BooleanField(default=False)),
                ('status_class', models.BooleanField(default=False)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Q', 'Quarto'), ('S', 'Sala'), ('CO', 'Copa'), ('B', 'Banheiro'), ('CZ', 'Cozinha'), ('U', 'Unissex')], max_length=2, null=True)),
                ('sub_secao', models.CharField(choices=[('A', 'Adulto'), ('J', 'Juvenil'), ('I', 'Infantil'), ('C', 'Casal'), ('S', 'Solteiro'), ('BE', 'Berco'), ('BB', 'Bebe')], max_length=2, null=True)),
                ('estilo', models.CharField(choices=[('C', 'Casual'), ('S', 'Social'), ('EF', 'Esporte Fino'), ('ES', 'Esportivo'), ('P', 'Praia')], max_length=2, null=True)),
                ('formato', models.CharField(choices=[('A', 'Ampla'), ('T', 'Tradicional'), ('F', 'Fina'), ('G', 'Gestante'), ('Q', 'Quadrada'), ('RE', 'Redonda'), ('RT', 'Retangular'), ('O', 'Oval')], max_length=2, null=True)),
                ('superior', models.CharField(choices=[('B', 'Baixa'), ('I', 'Intemediaria'), ('A', 'Alta'), ('E', 'Extra-alta')], max_length=1, null=True)),
                ('abertura', models.CharField(choices=[('AB', 'Aberta'), ('MA', 'Meia aberta'), ('F', 'Fechada'), ('D', 'Decote'), ('P', 'Polo'), ('V', 'V'), ('AM', 'Amamentacao')], max_length=2, null=True)),
                ('membro', models.CharField(choices=[('A', 'Alca'), ('MI', 'Mini'), ('C', 'Curta'), ('ME', 'Media'), ('3', '3/4'), ('L', 'Longa')], max_length=2, null=True)),
                ('detalhe', models.CharField(choices=[('BS', 'Bolso'), ('CG', 'Cargo'), ('CP', 'Capuz'), ('BJ', 'Bojo'), ('I', 'Inverno')], max_length=2, null=True)),
                ('material', models.CharField(choices=[('A', 'Algodao'), ('B', 'Brim'), ('J', 'Jeans'), ('MA', 'Malha'), ('MI', 'Moletin'), ('MO', 'Moleton'), ('SA', 'Sarja'), ('SI', 'Sintetico')], max_length=2, null=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
    ]
